### ISSUE TITLE
feature request: add "approved for data access" role fulfulled as requirement for linking accounts

### ISSUE THREAD

**Issue by bheavner** [UW-GAC/gregor-django#226]
not sure if this is a "role" or some other sort of drupal user profile item, but we'd like to be able to confirm that a user has been approved by the PI for data access before they can link their AnVIL account.

in the future, we'll likely want further integration, such as for offboarding or potentially assigning users to groups (such as uploaders), but this can be done manually for the time being (and for a long time, if this would be difficult).

**Comment by amstilp** [comment]
Closed by #235

The second paragraph is its own issue, so we can a new one when we need it.
